version: "3.5"

networks:
  default:
    name: kind
    external: true

volumes:
  data:

services:
  registry:
    container_name: kind-registry
    restart: always
    image: registry:2
    ports:
      - 5001:5000
    volumes:
      - data:/var/lib/registry
