apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    host: "127.0.0.1:5001"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
