version: "2.4"

services:
  app:
    build:
      context: .
    image: 127.0.0.1:5001/app:latest
    environment:
      DEBUG: "true"
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
