kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: app
  name: app-config
data:
  APP_CONFIG_FOO: Bar
  APP_CONFIG_HELLO: World
  DATABASE_USERNAME: dev
  DATABASE_PASSWORD: dev
  DATABASE_NAME: dev
